#!/usr/bin/fish

mkdir -p .cache
for i in (seq 1 101)
  set link "http://2016sv.icfpcontest.org/problem/view/$i"
  set cache ".cache/$i"
  echo $link
  if test -f $cache
    echo "Already in cache"
  else
    curl --silent $link -H 'Accept-Encoding: gzip, deflate, sdch' -H 'Accept-Language: en-US,en;q=0.8' -H 'Upgrade-Insecure-Requests: 1' -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36' -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8' -H 'Cookie: username="!fha2Cj83HT2i02Nln5P5ow==?gAJVCHVzZXJuYW1lcQFVAjI4cQKGcQMu"; xsrf_token="!1vJKx4o/nQjnCqhSNf0I+A==?gAJVCnhzcmZfdG9rZW5xAVUQZjRkNGI3ZWE1Y2VhZTJkN3EChnEDLg=="' -H 'Connection: keep-alive' --compressed > .cache/$i
    sleep 3
  end
end
